### ISSUE TITLE
rspec fails on a fresh build

### ISSUE THREAD

**Issue by bretweinraub** [RusticiSoftware/scormcloud-api-v2-client-ruby#11]
I've just installed the gem and have fired up rspec to validate that all tests have passed, and receive this:

```
Failures:

  1) RusticiSoftwareCloudV2::ApiClient#build_request when the content type is multipart sends multipart to request
     Failure/Error: request = Typhoeus::Request.new(url, req_opts)
     
       #<Typhoeus::Request (class)> received :new with unexpected arguments
         expected: (anything, hash_including(:multipart=>true))
              got: ("https://cloud.scorm.com/api/v2/test", {:headers=>{"Content-Type"=>"multipart/form-data", "User-Agent"=>"Swagger-Codegen/2.1.0/ruby"}, :meth...ssl_verifyhost=>2, :ssl_verifypeer=>true, :sslcert=>nil, :sslkey=>nil, :timeout=>0, :verbose=>false})
       Diff:
       @@ -1,13 +1,25 @@
       -["anything", "hash_including(:multipart=>true)"]
       +["https://cloud.scorm.com/api/v2/test",
       + {:headers=>
       +   {"Content-Type"=>"multipart/form-data",
       +    "User-Agent"=>"Swagger-Codegen/2.1.0/ruby"},
       +  :method=>:get,
       +  :params=>{},
       +  :params_encoding=>nil,
       +  :ssl_verifyhost=>2,
       +  :ssl_verifypeer=>true,
       +  :sslcert=>nil,
       +  :sslkey=>nil,
       +  :timeout=>0,
       +  :verbose=>false}]
       
     # ./lib/rustici_software_cloud_v2/api_client.rb:126:in `build_request'
     # ./spec/api_client_spec.rb:104:in `block (4 levels) in <top (required)>'
```

My environment:

```
rvm info

ruby-2.7.6@scormcloud-api-v2-client-ruby:

  system:
    uname:        "Darwin MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "12.4"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)"
    zsh:          "/bin/zsh => zsh 5.8.1 (x86_64-apple-darwin21.0)"
    remote_path:  "osx/12.4/x86_64"
    xcode:        "13.2.1"

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "3 months 23 days 20 hours 46 minutes 50 seconds ago"
    path:         
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.7.6p219"
    date:         "2022-04-12"
    platform:     "x86_64-darwin21"
    patchlevel:   "2022-04-12 revision c9c2245c0a"
    full_version: "ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin21]"
```

**Comment by mjschuetze102** [comment]
Hello Bret,

With version 2.0 of this library, we started keeping copies of the swagger template files to generate the library off of. The line which adds `:multipart=>true` to the request you listed above was accidentally left out. For what it's worth, the logic of the client goes off of `"Content-Type"=>"multipart/form-data"` rather than having `:multipart=>true`. I just did some spot checking and it doesn't appear that SCORM Cloud acts differently with the missing line added back in.

That being said, I am in the process of making a new update to the client library and will add back in the missing line. Were you seeing any problems outside of the scope of this test?

Sincerely,
Michael

**Comment by bretweinraub** [comment]
> Hello Bret,
> 
> With version 2.0 of this library, we started keeping copies of the swagger template files to generate the library off of. The line which adds `:multipart=>true` to the request you listed above was accidentally left out. For what it's worth, the logic of the client goes off of `"Content-Type"=>"multipart/form-data"` rather than having `:multipart=>true`. I just did some spot checking and it doesn't appear that SCORM Cloud acts differently with the missing line added back in.
> 

OK sounds good.

> That being said, I am in the process of making a new update to the client library and will add back in the missing line. Were you seeing any problems outside of the scope of this test?
> 
> Sincerely, Michael

Functionally no.   The documentation is sparse but the code is clear.

**Comment by mjschuetze102** [comment]
RSpec should be fixed with the latest release (3.0.0). Let me know if you run into any other issues

**Comment by bretweinraub** [comment]
I can confirm the test passes now.

**Comment by bretweinraub** [comment]
Thanks for your attention to this!
