### ISSUE TITLE
undefined method `build_from_hash' for RegistrationCompletion

### ISSUE THREAD

**Issue by rreinhardt9** [RusticiSoftware/scormcloud-api-v2-client-ruby#3]
Hello! We are trying to get up and running with v2 of the API and ran into a problem with the get registrations endpoint. When I try to retrieve registrations I get:

```
development > RusticiSoftwareCloudV2::RegistrationApi.new.get_registrations
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=https://cloud.scorm.com/api/v2/registrations response_code=200 return_code=ok total_time=0.729265
NoMethodError: undefined method `build_from_hash' for #<RusticiSoftwareCloudV2::RegistrationCompletion:0x00007fcb421c5c18>
from /Users/rossreinhardt/dev/lessonly/vendor/bundle/bundler/gems/scormcloud-api-v2-client-ruby-115901a746a8/lib/rustici_software_cloud_v2/models/registration_schema.rb:327:in `_deserialize'
```

Looking further into the code, it looks like that `RegistrationCompletion` and `RegistrationSuccess` are both two custom data types (mapped in the `RegistrationSchema#swagger_types` method)

The problem comes in when we get to the `else` branch of the `_deserialize` method (since they don't match any know types in that case statement) it tries to call `build_from_hash` on them. I don't know that calling that method on them makes sense anyway, since they will be strings and not hashes.

I'm not too familiar with swagger, but I think this gets generated from a central definition so individual contributions to this project might not help right?

I see two ways we could fix this:

- We could add these custom types to the case statement and make then respond to something like `to_s` in the deserialize method
- We could make their types just `String` instead of a custom `RegistrationCompletion` and `RegistrationSuccess` types.

Let me know what you think and if we can help!

**Comment by d-hansen** [comment]
I have submitted a PR to address this (so I could at least run the code), but as you note, this is actually a Swagger problem in that Swagger is not generating the right code.  They are using a slightly out-dated version of Swagger, so it may already be addressed if they were to just update Swagger and regenerate the output.  You are welcome to pull from my fork and build the gem and use that.

**Comment by mjschuetze102** [comment]
Closing as this should no longer be a problem.
