### ISSUE TITLE
Loosen requirement for JSON library 

### ISSUE THREAD

**Issue by rreinhardt9** [RusticiSoftware/scormcloud-api-v2-client-ruby#4]
We are trying to install this gem in our project, and currently the gem is restricted to using the JSON gem less limited to less that version 2.0. Unfortunately, that JSON library is up to 2.3.0 now and we have other dependencies that require greater that 2.0.

Would be we able to update the requirements for JSON in this SDK to be greater than 1.8, maybe something like this: https://github.com/lessonly/scormcloud-api-v2-client-ruby/commit/115901a746a8837a4dd21d1a11968aa57aadcf6d

Thanks! Let me know if opening a PR would be helpful.

**Comment by mjschuetze102** [comment]
Apologies for the delay here. We are currently in the process of updating all of our client libraries. As part of this process, we went through and made sure that our software would continue to work with the most up-to-date dependencies/ languages (for this one in particular JSON 2.3).

**Comment by mjschuetze102** [comment]
We've released a new version of the Ruby client library #9. Let us know if there are any issues you find when working with the updated version.
